Repository JYPark09/Cowdia, pull requests merged in 2021-08, with the labels that each got.

#18 Implement transpose, unary - operator, primitive & matrix addition, subtraction, and multiplication
  Includes/Cowdia/Math/Matrix.hpp
  Sources/Cowdia/Math/Matrix.cc
  Tests/UnitTests/Math/MatrixTests.cc
Labels: size/XL

#19 Refactoring Vector class
  Includes/Cowdia/Math/Vector.hpp
  Includes/Cowdia/Math/Vector2.hpp
  Includes/Cowdia/Math/Vector3.hpp
  Includes/Cowdia/Math/Vector4.hpp
  Includes/Cowdia/Math/VectorBase.hpp
  Sources/Cowdia/Math/Vector2.cc
  Sources/Cowdia/Math/Vector3.cc
  Sources/Cowdia/Math/Vector4.cc
  Tests/UnitTests/Math/MatrixTests.cc
  Tests/UnitTests/Math/VectorTests.cc
Labels: size/XL

#20 Refactoring Vector and Implement Quaternion
  Includes/Cowdia/Math/Angle.hpp
  Includes/Cowdia/Math/Constants.hpp
  Includes/Cowdia/Math/Quaternion.hpp
  Includes/Cowdia/Math/Vector2.hpp
  Includes/Cowdia/Math/Vector3.hpp
  Includes/Cowdia/Math/Vector4.hpp
  Sources/Cowdia/Math/Angle.cc
  Sources/Cowdia/Math/Quaternion.cc
  Sources/Cowdia/Math/Vector2.cc
  Sources/Cowdia/Math/Vector3.cc
  Sources/Cowdia/Math/Vector4.cc
  Tests/UnitTests/Math/AngleTests.cc
  Tests/UnitTests/Math/VectorTests.cc
Labels: size/L

#21 fix: clean up nodiscard attribute
  Includes/Cowdia/Math/Matrix.hpp
  Includes/Cowdia/Math/Quaternion.hpp
  Includes/Cowdia/Math/Vector2.hpp
  Includes/Cowdia/Math/Vector3.hpp
  Includes/Cowdia/Math/Vector4.hpp
Labels: size/M
