Repository JYPark09/Cowdia, pull requests merged in 2021-07, with the labels that each got.

#5 add matrix
  Includes/Cowdia/Math/Matrix.hpp
Labels: size/L

#6 Revert "Implement matrix"
  Includes/Cowdia/Math/Matrix.hpp
Labels: size/L

#8 Implement matrix
  Includes/Cowdia/Math/Matrix.hpp
  Includes/Cowdia/Math/Vector.hpp
  Tests/UnitTests/Math/MatrixTests.cc
Labels: size/L

#9 Implement literal addition, subtraction & matrix multiplication
  Includes/Cowdia/Math/Matrix.hpp
  Includes/Cowdia/Math/Vector.hpp
  Tests/UnitTests/Math/MatrixTests.cc
  Tests/UnitTests/Math/VectorTests.cc
Labels: size/L

#15 Implement DirectX12 Renderer
  CMake/FindD3D12.cmake
  CMakeLists.txt
  CMakeSettings.json
  Extensions/D3D12Renderer/CMakeLists.txt
  Extensions/D3D12Renderer/D3D12Exception.cc
  Extensions/D3D12Renderer/D3D12Exception.hpp
  Extensions/D3D12Renderer/D3D12RenderSystem.cc
  Extensions/D3D12Renderer/D3D12RenderSystem.hpp
  Extensions/D3D12Renderer/D3D12RenderWindow.cc
  Extensions/D3D12Renderer/D3D12RenderWindow.hpp
  Extensions/D3D12Renderer/D3D12Renderer.cc
  Extensions/D3D12Renderer/D3D12Renderer.hpp
  Extensions/TestApp/main.cc
  Includes/Cowdia/Core/Exception.hpp
  Includes/Cowdia/Core/LogManager.hpp
  Includes/Cowdia/Rendering/RenderSystem.hpp
  Includes/Cowdia/Rendering/RenderWindow.hpp
  Includes/Cowdia/Rendering/Renderer.hpp
  Includes/Cowdia/Utils/ComPtr.hpp
  Sources/Cowdia/Core/Engine.cc
  Sources/Cowdia/Core/Exception.cc
  Sources/Cowdia/Core/LogManager.cc
  Sources/Cowdia/Rendering/RenderWindow.cc
Labels: size/XL

#17 Implement basic scene system
  Extensions/D3D12Renderer/D3D12RenderSystem.cc
  Extensions/D3D12Renderer/D3D12RenderWindow.cc
  Extensions/TestApp/main.cc
  Includes/Cowdia/Core/Application.hpp
  Includes/Cowdia/Core/Engine.hpp
  Includes/Cowdia/Core/Exception.hpp
  Includes/Cowdia/Game/Scene.hpp
  Includes/Cowdia/Game/SceneManager.hpp
  Sources/Cowdia/Core/Engine.cc
  Sources/Cowdia/Core/Exception.cc
  Sources/Cowdia/Core/Log.cc
  Sources/Cowdia/Game/SceneManager.cc
Labels: size/L

#10 Update README
  README.md
Labels: size/M
